# Generated by Django 2.2.7 on 2019-11-12 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191111_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectattachment',
            options={'ordering': ('created_at',), 'verbose_name': 'Anexo', 'verbose_name_plural': 'Anexos'},
        ),
    ]
